title: "AKDSFramework Documentation"
logo: images/logo.png
author: theroyakash
copyright: "2020"
email: royakashappleid@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  This is an example book built with Jupyter Books.

execute:
  execute_notebooks: "off"

html:
  favicon: images/favicon.ico

latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex