name: AKDSFramework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: testing AKDSFramework modules
      run: |
        python tests/test_heap.py
        python tests/test_linkedlist.py
        python tests/test_sort.py
        python tests/test_queue.py
        python tests/tests_graph.py
        python tests/test_dijkstra.py
